### ISSUE TITLE
Issue with Liquid confluence plugin behavior

### ISSUE THREAD

**Issue by X223951** [emdgroup-liquid/liquid-confluence#101]
An issue with the Liquid confluence plugin behavior, we cannot able to change the Top bar color of our confluence.

**Steps to reproduce the behavior**

Go to Space Tools --> Look and Feel --> Color scheme --> Custom color scheme --> Edit --> Change the Top bar color

**Expected behavior**

After changing the Top bar color in the **space or Global level** It should change the color of the Confluence top bar. (PFA (Top bar color in Space level, Top bar color in Global Application level))

**Actual behavior**

1. After changing the Top bar color of the space, It is not changing the color of the top bar. (PFA (used Global color scheme in space))
2. After changing the Top bar color in the Global Application level, It is not changing the color of the confluence top bar color. (PFA (color not changing in global app level))

**Screenshots**

<img width="602" alt="color not changing in global app level" src="https://user-images.githubusercontent.com/132052133/235100822-c0d29ce3-7ab3-4ea1-bce6-39ebe3ce2d6a.PNG">
<img width="601" alt="Top bar color in Global Application level" src="https://user-images.githubusercontent.com/132052133/235100839-27f62d5d-4903-4c68-bb91-7c6d6336ea05.PNG">
<img width="854" alt="Top bar color in space level" src="https://user-images.githubusercontent.com/132052133/235100843-3492d3fc-8c3b-47e2-8788-7f601c880369.PNG">

**Details about device, OS, browser (including versions)**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

Here is our Confluence application links.
https://wiki.merckgroup.com/confluence/
https://wiki-test.merckgroup.com/confluence/

**Comment by borisdiakur** [comment]
:tada: This issue [has been resolved](https://github.com/emdgroup-liquid/liquid-confluence/commit/8550f2cf833ff297a95d45f55c5e34d732c448e8) in version 1.0.4 :tada:

The release is available on the [Atlassian Marketplace](https://marketplace.atlassian.com/apps/1230416/liquid-confluence?tab=overview&hosting=datacenter) or as a [jar file download](https://marketplace.atlassian.com/download/apps/1230416/version/1000052) :package::rocket:
